# Generated by Django 5.0.6 on 2024-05-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_create_at_material_image_material_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='slug name'),
        ),
    ]
