# Generated by Django 5.0.6 on 2024-05-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_material_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.CharField(blank=True, default='<django.db.models.fields.charfield>', max_length=150, null=True, unique=True, verbose_name='slug name'),
        ),
    ]
