# Generated by Django 5.0.4 on 2024-05-06 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название категории')),
                ('description', models.TextField(max_length=250, verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название продукта')),
                ('description', models.TextField(max_length=250, verbose_name='описание продукта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение продукта')),
                ('price', models.IntegerField(max_length=10, verbose_name='цена продукта')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('update_at', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
