# Generated by Django 5.0.6 on 2024-05-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_views_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='slug name'),
        ),
    ]
