# Generated by Django 5.0.6 on 2024-05-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, default='<django.db.models.fields.charfield>', max_length=30, null=True, unique=True, verbose_name='slug name'),
        ),
    ]
