# Generated by Django 5.0.6 on 2024-05-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'версия продукта', 'verbose_name_plural': 'версии продукта'},
        ),
    ]
