# Generated by Django 4.2.2 on 2024-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_version_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, default='admin@gmail.com', max_length=40, null=True, verbose_name='опубликовал'),
        ),
    ]
