# Generated by Django 4.2.2 on 2024-06-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Может активировать/деактивировать публикацию'), ('change_description', 'Может изменять описание продукта'), ('change_category', 'Может изменять категорию продукта')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='публикация'),
        ),
    ]
